version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
      - NODE_ENV=development
      - NEO4J_URI=bolt://graph-db:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      # Mount source code for hot reload
      - ./backend/src:/app/src:ro
      - ./backend/tsconfig.json:/app/tsconfig.json:ro
      - ./backend/nest-cli.json:/app/nest-cli.json:ro
      # Use named volume for node_modules to avoid overwriting
      - backend_node_modules:/app/node_modules
    # Override healthcheck for development (less strict)
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend_node_modules:
